language: node_js
sudo: false
dist: trusty
addons:
  addons:
  sonarcloud:
    organization: "ruchikawipro-github"
   
jdk:
  - oraclejdk9
  sauce_connect:
    username: "RuchikaSauceLabs"
    access_key: "3ce71427-cfbb-491e-8c11-7e487b38bb59"
    sauce_connect: true
node_js:
  - "stable"
scripts:
  - "start"
  - "test"
  - "sonar-scanner"
