language: node_js
sudo: required
dist: trusty
addons:
  sonarcloud:
    organization: "ruchikawipro-github"
    token:
      secure: "a62d8ffac409385843b93a450701060eac178202"
jdk:
  - oraclejdk8
node_js:
  - "node"
script:
  - "start"
  - "test"
  - "sonar-scanner"
 
